# Generated by Django 5.2.17 on 2026-09-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_platformsetting_mikhmon_base_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformsetting",
            name="mikhmon_base_domain",
            field=models.CharField(
                default="tikzone.net",
                help_text="Ex: tikzone.net (les sous-domaines seront https://espace.tikzone.net)",
                max_length=100,
                verbose_name="Domaine de base Mikhmon",
            ),
        ),
    ]
