# Generated by Django 5.2.17 on 2026-09-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_platformsetting_mikhmon_base_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="external_reference",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Référence externe passerelle"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("ORANGE_MONEY", "Orange Money"),
                    ("WAVE", "Wave"),
                    ("MOOV", "Moov Money"),
                    ("CARD", "Carte Bancaire"),
                    ("LIGDICASH", "LigdiCash (Orange, Moov, Wave, MTN, Telecel)"),
                    ("OFFLINE", "Paiement hors-ligne / Reçu"),
                    ("WALLET", "Débit direct du Wallet"),
                ],
                default="WALLET",
                max_length=20,
                verbose_name="Moyen de paiement",
            ),
        ),
    ]
