# Generated by Django 5.2.17 on 2026-09-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
        ("instances", "0002_mikhmoninstance_client_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Espace assigné à ce gérant (confinement strict).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managers",
                to="instances.mikhmoninstance",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Nom d'utilisateur / Pseudo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Administrateur"),
                    ("TECHNICIAN", "Technicien / Installateur"),
                    ("OWNER", "Propriétaire WiFi Zone"),
                    ("CLIENT_MANAGER", "Gérant de Point de Vente / Client"),
                ],
                default="OWNER",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
