# Generated by Django 5.2.17 on 2026-09-24 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_managed_instance_user_username_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Adresse Email"
                    ),
                ),
                ("otp_code", models.CharField(max_length=10, verbose_name="Code OTP")),
                (
                    "registration_data",
                    models.JSONField(
                        default=dict, verbose_name="Données d'inscription temporaires"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Nombre de tentatives"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Est validé"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Date d'expiration")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "OTP d'inscription",
                "verbose_name_plural": "OTPs d'inscription",
                "ordering": ["-created_at"],
            },
        ),
    ]
