from django.urls import re_path
from .views import (
    CreateRouterView,
    PingRouterView,
    RenewRouterView,
    RouterDetailView,
    RouterDisconnectActiveView,
    RouterGenerateTicketsView,
    RouterHotspotOverviewView,
    RouterHotspotProfilesView,
    RouterHotspotUsersView,
    RouterListView,
    RouterLogsView,
    RouterRebootView,
    RouterSalesReportPdfView,
    RouterSalesReportView,
    RouterSystemInfoView,
    RouterUpdateUserLimitsView,
    RouterSaaSTicketsView,
    RouterRadiusSetupScriptView,
    VpnSyncListView,
)

urlpatterns = [
    re_path(r"^$", RouterListView.as_view(), name="router-list"),
    re_path(r"^create/?$", CreateRouterView.as_view(), name="router-create"),
    re_path(r"^vpn-sync/?$", VpnSyncListView.as_view(), name="router-vpn-sync"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/?$", RouterDetailView.as_view(), name="router-detail"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/renew/?$", RenewRouterView.as_view(), name="router-renew"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/ping/?$", PingRouterView.as_view(), name="router-ping"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/system-info/?$", RouterSystemInfoView.as_view(), name="router-system-info"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/hotspot/overview/?$", RouterHotspotOverviewView.as_view(), name="router-hotspot-overview"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/hotspot/users/?$", RouterHotspotUsersView.as_view(), name="router-hotspot-users"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/hotspot/users/(?P<username>[^/]+)/limits/?$", RouterUpdateUserLimitsView.as_view(), name="router-user-limits"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/hotspot/generate/?$", RouterGenerateTicketsView.as_view(), name="router-hotspot-generate"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/hotspot/profiles/?$", RouterHotspotProfilesView.as_view(), name="router-hotspot-profiles"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/hotspot/active/(?P<active_id>[^/]+)/disconnect/?$", RouterDisconnectActiveView.as_view(), name="router-disconnect-active"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/saas-tickets/?$", RouterSaaSTicketsView.as_view(), name="router-saas-tickets"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/radius-script/?$", RouterRadiusSetupScriptView.as_view(), name="router-radius-script"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/reports/?$", RouterSalesReportView.as_view(), name="router-sales-report"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/reports/pdf/?$", RouterSalesReportPdfView.as_view(), name="router-sales-report-pdf"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/logs/?$", RouterLogsView.as_view(), name="router-logs"),
    re_path(r"^(?P<router_id>[0-9a-f-]+)/reboot/?$", RouterRebootView.as_view(), name="router-reboot"),
]

