# Generated by Django 5.2.17 on 2026-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routers", "0002_vpncredential_wireguard_listen_port_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpncredential",
            name="assigned_ip",
            field=models.GenericIPAddressField(
                protocol="IPv4", verbose_name="IP VPN Assignée"
            ),
        ),
        migrations.AlterField(
            model_name="vpncredential",
            name="vpn_server",
            field=models.CharField(
                default="vpn.tikzone.net", max_length=100, verbose_name="Serveur VPN"
            ),
        ),
    ]
