# Generated by Django 5.2.17 on 2026-09-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routers", "0003_alter_vpncredential_assigned_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="hotspot_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Nom Commercial Hotspot",
            ),
        ),
    ]
