# Generated by Django 5.2.17 on 2026-09-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routers", "0004_router_hotspot_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpncredential",
            name="vpn_server",
            field=models.CharField(
                default="187.7.20.53", max_length=100, verbose_name="Serveur VPN"
            ),
        ),
    ]
