# Generated by Django 5.2.17 on 2026-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routers", "0005_alter_vpncredential_vpn_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="api_password",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="Mot de passe API RouterOS",
            ),
        ),
        migrations.AddField(
            model_name="router",
            name="api_user",
            field=models.CharField(
                default="admin",
                max_length=50,
                verbose_name="Nom d'utilisateur API RouterOS",
            ),
        ),
    ]
