# Generated by Django 5.2.17 on 2026-09-21 01:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routers", "0006_router_api_password_router_api_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotspotBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Nom ou Référence du Lot",
                    ),
                ),
                (
                    "profile_name",
                    models.CharField(
                        default="default", max_length=100, verbose_name="Nom du Profil"
                    ),
                ),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[
                            ("single", "Code unique / PIN (1 champ)"),
                            ("dual", "Utilisateur & Mot de passe distincts (2 champs)"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="Mode d'Authentification",
                    ),
                ),
                (
                    "code_length",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="Longueur des codes"
                    ),
                ),
                (
                    "time_limit",
                    models.CharField(
                        default="3h", max_length=50, verbose_name="Limite de Durée"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=10,
                        verbose_name="Prix Unitaire (FCFA)",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de Tickets"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Commentaire / Libellé"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Génération"
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspot_batches",
                        to="routers.router",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot de Tickets Hotspot",
                "verbose_name_plural": "Lots de Tickets Hotspot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HotspotTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="Code Ticket / Identifiant",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=64, verbose_name="Mot de Passe"),
                ),
                (
                    "profile_name",
                    models.CharField(
                        default="default", max_length=100, verbose_name="Profil Associé"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Disponible (Non utilisé)"),
                            ("ACTIVE", "Actif (En cours d'utilisation)"),
                            ("EXPIRED", "Expiré (Temps écoulé)"),
                            ("REVOKED", "Révoqué (Désactivé)"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        default=10800, verbose_name="Limite de Temps Totale (secondes)"
                    ),
                ),
                (
                    "uptime_used_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Temps Déjà Consommé (secondes)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=10,
                        verbose_name="Prix de Vente (FCFA)",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Commentaire"
                    ),
                ),
                (
                    "first_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Première Connexion"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière Activité"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'Expiration Finale"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Adresse MAC Client",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dernière IP Assignée"
                    ),
                ),
                (
                    "bytes_in",
                    models.BigIntegerField(
                        default=0, verbose_name="Octets Téléchargés (Download)"
                    ),
                ),
                (
                    "bytes_out",
                    models.BigIntegerField(
                        default=0, verbose_name="Octets Envoyés (Upload)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière Mise à Jour"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="routers.hotspotbatch",
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspot_tickets",
                        to="routers.router",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Hotspot SaaS",
                "verbose_name_plural": "Tickets Hotspot SaaS",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["code", "status"], name="routers_hot_code_ff1358_idx"
                    ),
                    models.Index(
                        fields=["router", "status"],
                        name="routers_hot_router__fd801a_idx",
                    ),
                ],
            },
        ),
    ]
