# Generated by Django 5.2.17 on 2026-09-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routers", "0007_hotspotbatch_hotspotticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="hotspot_type",
            field=models.CharField(
                choices=[
                    ("RADIUS", "Moteur Cloud RADIUS (Recommandé)"),
                    ("STANDALONE", "Moteur Local RouterOS"),
                ],
                default="RADIUS",
                max_length=20,
                verbose_name="Type de Moteur Hotspot",
            ),
        ),
    ]
