# Generated by Django 5.2.17 on 2026-09-22 01:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routers", "0008_router_hotspot_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudHotspotProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du Forfait"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        default=100,
                        max_digits=10,
                        verbose_name="Prix de Vente (FCFA)",
                    ),
                ),
                (
                    "rate_limit",
                    models.CharField(
                        blank=True,
                        default="2M/2M",
                        max_length=50,
                        verbose_name="Limite de Débit",
                    ),
                ),
                (
                    "session_timeout",
                    models.CharField(
                        default="1h", max_length=50, verbose_name="Durée de Connexion"
                    ),
                ),
                (
                    "session_timeout_seconds",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="Durée en Secondes"
                    ),
                ),
                (
                    "shared_users",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Appareils en Simultané"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Actif (Disponible à la vente)"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Description / Libellé",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière Mise à Jour"
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_profiles",
                        to="routers.router",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Hotspot Cloud",
                "verbose_name_plural": "Profils Hotspot Cloud",
                "ordering": ["price", "created_at"],
                "unique_together": {("router", "name")},
            },
        ),
    ]
