# Generated by Django 5.2.17 on 2026-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mikhmoninstance",
            name="client_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Nom du propriétaire / Client",
            ),
        ),
        migrations.AddField(
            model_name="mikhmoninstance",
            name="client_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                verbose_name="Numéro WhatsApp du propriétaire",
            ),
        ),
        migrations.AlterField(
            model_name="mikhmoninstance",
            name="admin_password",
            field=models.CharField(
                default="mikroot2026",
                max_length=100,
                verbose_name="Mot de passe Espace",
            ),
        ),
        migrations.AlterField(
            model_name="mikhmoninstance",
            name="admin_user",
            field=models.CharField(
                default="admin", max_length=50, verbose_name="Nom d'utilisateur Espace"
            ),
        ),
    ]
